version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=nils.chr.bogen@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`api.bogsynth.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`api.bogsynth.com`) && PathPrefix(`/container1`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

  pb:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pb.rule=Host(`api.bogsynth.com`) && PathPrefix(`/pb`)"  # Match the path prefix /pb
      - "traefik.http.routers.pb.entrypoints=websecure"
      - "traefik.http.routers.pb.tls.certresolver=myresolver"
      - "traefik.http.middlewares.pb-stripprefix.stripprefix.prefixes=/pb"  # Strip /pb prefix
      - "traefik.http.routers.pb.middlewares=pb-stripprefix"  # Apply the middleware
      - "traefik.http.services.pb.loadbalancer.server.port=8080"  # Specify the backend port