version: '3.3'
services:
  1ks8mousrwm02mv:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/1ks8mousrwm02mv/data:/pb/pb_data
      - ${PROJECT}/data/1ks8mousrwm02mv/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - >-
        traefik.http.routers.troubadour.rule=Host(`${HOST}`) &&
        PathPrefix(`/troubadour`)
      - traefik.http.routers.troubadour.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.troubadour.middlewares=troubadour-stripprefix
      - >-
        traefik.http.middlewares.troubadour-stripprefix.stripprefix.prefixes=/troubadour
      - traefik.http.services.troubadour.loadbalancer.server.port=8080
  kc81cxas6pufkng:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/kc81cxas6pufkng/data:/pb/pb_data
      - ${PROJECT}/data/kc81cxas6pufkng/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - traefik.http.routers.nils.rule=Host(`${HOST}`) && PathPrefix(`/nils`)
      - traefik.http.routers.nils.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.nils.middlewares=nils-stripprefix
      - traefik.http.middlewares.nils-stripprefix.stripprefix.prefixes=/nils
      - traefik.http.services.nils.loadbalancer.server.port=8080
  ef0m7qml9dl4k3u:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/ef0m7qml9dl4k3u/data:/pb/pb_data
      - ${PROJECT}/data/ef0m7qml9dl4k3u/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - traefik.http.routers.kris.rule=Host(`${HOST}`) && PathPrefix(`/kris`)
      - traefik.http.routers.kris.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.kris.middlewares=kris-stripprefix
      - traefik.http.middlewares.kris-stripprefix.stripprefix.prefixes=/kris
      - traefik.http.services.kris.loadbalancer.server.port=8080
  66a6c90qdjk80gt:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/66a6c90qdjk80gt/data:/pb/pb_data
      - ${PROJECT}/data/66a6c90qdjk80gt/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - traefik.http.routers.k2.rule=Host(`${HOST}`) && PathPrefix(`/k2`)
      - traefik.http.routers.k2.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.k2.middlewares=k2-stripprefix
      - traefik.http.middlewares.k2-stripprefix.stripprefix.prefixes=/k2
      - traefik.http.services.k2.loadbalancer.server.port=8080
networks:
  backend: null
