version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=backend"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=myauth"
      - "traefik.http.middlewares.myauth.basicauth.removeheader=true"
      - "traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$05$$g/gXhF6YSMikWAYYnQcY1.EIhdigVouuyuK.CaqQBlZ5pP8Nsnoli"


  whoami:
    image: containous/whoami
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  backend:
