version: '3.3'
services:
  lol:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - '9000:8080'
    networks:
      - backend
    volumes:
      - ./data/lol:/pb/pb_data
    labels:
      - traefik.enable=true
      - traefik.http.routers.lol.rule=Host(`localhost`) && PathPrefix(`/lol`)
      - traefik.http.routers.lol.entrypoints=web
      - traefik.http.middlewares.lol-stripprefix.stripprefix.prefixes=/lol
      - traefik.http.routers.lol.middlewares=lol-stripprefix
      - traefik.http.services.lol.loadbalancer.server.port=8080
networks:
  backend: null
