version: "3.3"
services:
  admin_pb:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes: 
      - ./data/admin:/pb/pb_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin_pb.rule=Host(`localhost`) && PathPrefix(`/admin_pb`)"  # Match the path prefix /admin
      - "traefik.http.routers.admin_pb.entrypoints=web"
      - "traefik.http.middlewares.admin_pb-stripprefix.stripprefix.prefixes=/admin_pb"  # Strip /admin prefix
      - "traefik.http.routers.admin_pb.middlewares=admin_pb-stripprefix"  # Apply the middleware
      - "traefik.http.services.admin_pb.loadbalancer.server.port=8080"  # Specify the backend port

  admin:
    restart: always
    build:
      context: ./admin_bun
      dockerfile: Dockerfile
    networks:
      - backend
    volumes: 
      - ./data/.compose:/admin/output
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`localhost`) && PathPrefix(`/admin`)"  # Match the path prefix /admin
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/admin"  # Strip /admin prefix
      - "traefik.http.routers.admin.middlewares=admin-stripprefix"  # Apply the middleware
      - "traefik.http.services.admin.loadbalancer.server.port=8081"  # Specify the backend port
    depends_on:
      - admin_pb

networks:
  backend:
