version: '3.3'
services:
  ef0m7qml9dl4k3u:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/ef0m7qml9dl4k3u/data:/pb/pb_data
      - ${PROJECT}/data/ef0m7qml9dl4k3u/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - traefik.http.routers.kris.rule=Host(`${HOST}`) && PathPrefix(`/kris`)
      - traefik.http.routers.kris.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.kris.middlewares=kris-stripprefix
      - traefik.http.middlewares.kris-stripprefix.stripprefix.prefixes=/kris
      - traefik.http.services.kris.loadbalancer.server.port=8080
  66a6c90qdjk80gt:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    networks:
      - backend
    volumes:
      - ${PROJECT}/data/66a6c90qdjk80gt/data:/pb/pb_data
      - ${PROJECT}/data/66a6c90qdjk80gt/public:/pb/pb_public
    labels:
      - com.pocketkube
      - traefik.enable=true
      - traefik.http.routers.k2.rule=Host(`${HOST}`) && PathPrefix(`/k2`)
      - traefik.http.routers.k2.entrypoints=${ENTRYPOINTS}
      - traefik.http.routers.k2.middlewares=k2-stripprefix
      - traefik.http.middlewares.k2-stripprefix.stripprefix.prefixes=/k2
      - traefik.http.services.k2.loadbalancer.server.port=8080
networks:
  backend: null
