version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    env_file:
      - .env
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=backend"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=${ENTRYPOINTS}"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=myauth"
      - "traefik.http.middlewares.myauth.basicauth.removeheader=true"
      - "traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$05$$1R3OYP8FmiAzpQmxcaDJIuEpturNMNAG9ecpfsyxG2CHBZy3rh4ya"

#       - "traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$05$$reP17WErqC1z7uU5Kl0w2Og.EAkNHhAS/hXzCgLUylJ6fYTvZB5Sq"

  whoami:
    image: containous/whoami
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=${ENTRYPOINTS}"

networks:
  backend:
